# yaml-language-server: $schema=https://docs.mergify.com/mergify-configuration-openapi.json

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - and:
          - author=dependabot[bot]
          - check-success=MegaLinter
          - '#approved-reviews-by>=1'
    actions:
      merge:
        method: squash
