---
# yaml-language-server: $schema=https://raw.githubusercontent.com/oxsecurity/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json

# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default

DISABLE:
  - TERRAFORM
#   - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
#   - SPELL # Comment to enable checks of spelling mistakes

# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass

DISABLE_LINTERS:
  - REPOSITORY_SEMGREP # doesn't work for me currently

FILEIO_REPORTER: false
FILTER_REGEX_EXCLUDE: '(megalinter-reports)'
IGNORE_GITIGNORED_FILES: true
MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md)'
SPELL_LYCHEE_FILTER_REGEX_EXCLUDE: '(\.github/workflows|\.mega-linter\.yml)'
SHOW_ELAPSED_TIME: true
YAML_V8R_FILTER_REGEX_EXCLUDE: '(\.prettierrc\.yaml)'
