blank_issues_enabled: false
contact_links:
  - name: Project documentation
    url: https://github.com/mauwii/act-docker-images/blob/main/README.md
    about: At the moment the only documentation besides comments is the repository's readme.
  - name: nektos/act repository
    url: https://github.com/nektos/act
    about: The great tool which enables you to run GitHub workflows locally.
  - name: nektos/act documentation
    url: https://nektosact.com/beginner/index.html
    about: Docs for nektos/act to find out more about how to actually use this tool.
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions regarding the GitHub Platform here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities of the GitHub Platform here.
