---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: ci

on:
  push:
    paths:
      - '**/Dockerfile'
      - '**/toolsets/*.json'
      - '**/.github/workflows/ci.yml'
      - '**/docker-bake.hcl'
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  pull-requests: write

env:
  REGISTRY: ${{ vars.DOCKERHUB_USER && 'docker.io' || 'ghcr.io' }}
  SHA: ${{ github.event.pull_request.head.sha || github.event.after || github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ vars.DOCKERHUB_USER && 'docker.io' || 'ghcr.io' }}
    outputs:
      matrix: ${{ steps.platforms.outputs.matrix }}
    steps:
      # kics-scan ignore-line
      - uses: actions/checkout@v4

      - name: Set up QEMU
        # kics-scan ignore-line
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        # kics-scan ignore-line
        uses: docker/setup-buildx-action@v3.0.0

      - name: get docker binary path
        id: docker-binary-path
        run: echo "DOCKER_BINARY_PATH=$(which docker)" >> "$GITHUB_OUTPUT"

      - name: bake-file with empty env
        id: bake-file-no-env
        run: env -i ${{ steps.docker-binary-path.outputs.DOCKER_BINARY_PATH }} buildx bake --print

      - name: verify tag ends on -local
        run: |
          BAKE_TAG="$(env -i ${{ steps.docker-binary-path.outputs.DOCKER_BINARY_PATH }} buildx bake --print  | jq -r '[.target[].tags[]][0]')"
          [[ "${BAKE_TAG}" == *"-local" ]] || exit 1

      # - name: bake-file with test ref
      #   id: bake-file-test-tag
      #   run: printf "BAKE_OUTPUT=%s\n" "$(env -i ${{ steps.docker-binary-path.outputs.DOCKER_BINARY_PATH }} buildx bake --print | jq -c)" >> "$GITHUB_OUTPUT"
      #   env:
      #     GITHUB_BASE_REF: 'test'

      # - name: verify tag ends on -test
      #   run: |
      #     BAKE_TAG="$(echo '${{ steps.bake-file-test-tag.outputs.BAKE_OUTPUT }}' | jq -r '[.target[].tags[]][0]')"
      #     [[ "${BAKE_TAG}" == *"-test" ]] || exit 1

      - name: bake-file
        run: docker buildx bake --print
        env:
          GITHUB_SHA: ${{ env.SHA }}

      - name: validate tag
        run: |
          BAKE_TAG="$(docker buildx bake --print | jq -r '[.target[].tags[]][0]')"
          [[ "${BAKE_TAG}" == *"-${{ github.ref_name}}" ]] || exit 1

      - name: Create matrix
        id: platforms
        run: printf "matrix=%s\n" "$(docker buildx bake linux-platforms --print | jq -cr '.target."linux-platforms".platforms')" >>"${GITHUB_OUTPUT}"

      - name: Show matrix
        run: |
          echo ${{ steps.platforms.outputs.matrix }}
  build:
    needs: test
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     platforms: ${{ fromJson(needs.test.outputs.matrix) }}
    #     # platforms: ${{ github.event_name == 'pull_request' && fromJson('["linux/amd64", "linux/arm64"]') || fromJson('["linux/amd64,linux/arm64"]') }}
    env:
      BUILDKIT_PROGRESS: plain
    steps:
      - uses: actions/checkout@v4

      - name: Free up disk space
        # kics-scan ignore-line
        uses: ./.github/actions/free-space
        with:
          deleteDotnet: 'true'
          deleteAndroid: 'true'

      - name: Set up QEMU
        # kics-scan ignore-line
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        # kics-scan ignore-line
        uses: docker/setup-buildx-action@v3.0.0
        with:
          # driver: ${{ github.event_name == 'pull_request' && 'docker' || 'docker-container' }}
          driver: docker-container
          driver-opts: image=moby/buildkit:v0.12.2
          install: true
          use: true
          cleanup: true
          # platforms: ${{ matrix.platforms }}

      # Login against a container registry
      # https://github.com/docker/login-action
      # kics-scan ignore-line
      - uses: docker/login-action@v3.0.0
        name: Login to ${{ env.REGISTRY }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.DOCKERHUB_USER || github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN || secrets.GITHUB_TOKEN }}
          logout: true

      # # Get the architecture to use for the cache tag
      # - name: get arch
      #   id: cache-arch
      #   if: github.event_name == 'pull_request'
      #   run: >-
      #     printf "CACHE_ARCH=%s\n" "$(
      #     docker run
      #     --quiet
      #     --platform ${{ matrix.platforms }}
      #     --rm
      #     "${PULL_IMAGE}"
      #     /bin/bash -c "dpkg --print-architecture"
      #     )" >> "$GITHUB_OUTPUT"
      #   env:
      #     PULL_IMAGE: ubuntu:22.04

      # kics-scan ignore-line
      - uses: docker/bake-action@v4.0.0
        name: Build and Push
        with:
          files: docker-bake.hcl
          push: ${{ github.event_name != 'pull_request' && github.actor != 'nektos/act' }}
          sbom: true
          set: |
            ubuntu*.output=type=${{ env.OUTPUT_TYPE }},${{ env.OUTPUT_KIND }}
            ${{ github.event_name == 'pull_request' && github.actor != 'nektos/act' && '*.cache-to=type=registry,mode=max' || '' }}
          #   ubuntu*.platform=${{ matrix.platforms }}
        env:
          OUTPUT_KIND: ${{ github.event_name != 'pull_request' && 'push=true' || format('dest={0}',  env.FROM_IMAGE_PATH) }}
          OUTPUT_TYPE: ${{ github.event_name != 'pull_request' && 'registry' || 'docker' }}
          # REGISTRY_IMAGE: ${{ format('{0}/{1}', env.REGISTRY, env.IMAGE_REPOSITORY) }}

      # # vulnerability scanning to verify PRs
      # - name: Docker Scout
      #   id: docker-scout
      #   uses: docker/scout-action@v0.23.4
      #   if: github.event_name == 'pull_request'
      #   with:
      #     platform: ${{ matrix.platforms }}
      #     command: quickview
      #     image: ${{ env.FROM_IMAGE_PATH }}
      #     type: archive
      #     to: ${{ env.TO_TAG }}
      #     ignore-unchanged: true
      #     only-severities: critical
      #     write-comment: ${{ github.actor != 'nektos/act' }}
      #     summary: ${{ github.actor != 'nektos/act' }}
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     organization: ${{ vars.DOCKERHUB_USER || github.repository_owner }}

  approve-pr:
    name: Approve PR
    runs-on: ubuntu-latest
    needs: [build]
    if: github.actor != 'nektos/act' && contains(fromJson('["mauwii","dependabot[bot]"]'), github.triggering_actor) && github.event_name == 'pull_request' &&  needs.build.result == 'success'
    permissions:
      contents: read
      pull-requests: write
      actions: write
    steps:
      # approve the PR (there is still a code-owner review necessary)
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # auto merge dependabot PRs
      - name: Merge DependaBot
        if: github.actor == 'dependabot[bot]' &&  needs.build.result == 'success'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
