name: ci

on:
  push:
    branches: [main, develop]
    paths:
      - '**/Dockerfile'
  pull_request:
    paths:
      - '**/Dockerfile'
      - '**/.github/workflows/ci.yml'

permissions:
  contents: write
  pull-requests: write
  packages: write

env:
  IMAGE_NAME: ${{ github.repository_owner }}/ubuntu-act

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.triggering_actor != 'github-actions[bot]'
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        from-tag: [act-22.04, act-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create metadata for Docker Buildx
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_NAME }}
            ghcr.io/${{ env.IMAGE_NAME }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./linux/ubuntu/Dockerfile
          platforms: ${{ matrix.platform}}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            FROM_TAG=${{ matrix.from-tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
          provenance: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          outputs: type=image,name=${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=${{ github.event_name != 'pull_request' }}

      - name: Export digest
        run: |
          mkdir -p /tmp/digests/${{ matrix.from-tag }}
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${{ matrix.from-tag }}/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: digests
          path: /tmp/digests/${{ matrix.from-tag }}/*
          if-no-files-found: error
          retention-days: 1

  manifests:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      matrix:
        from-tag: [act-22.04, act-20.04]
        include:
          - from-tag: act-22.04
            image-tag: '22.04'
          - from-tag: act-20.04
            image-tag: '20.04'
    if: github.event_name != 'pull_request'
    steps:
      - name: Download digests
        uses: actions/download-artifact@v3
        with:
          name: digests
          path: /tmp/digests/${{ matrix.from-tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create tags for docker buildx
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_NAME }}
            ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' && matrix.from-tag == 'act-22.04' }}
            type=raw,value=${{ matrix.image-tag }}
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=${{ matrix.image-tag }}-
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digests/${{ matrix.from-tag }}
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.IMAGE_NAME }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}

  merge-pr:
    name: Merge Pull Request
    runs-on: ubuntu-latest
    needs: [build]
    if: github.triggering_actor == 'mauwii' && github.event_name == 'pull_request' &&  needs.build.result == 'success'
    steps:
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: ${{ github.base_ref == 'develop' && 'squash merge' || 'merge' }} PR
        run: gh pr merge --auto --${{ github.base_ref == 'develop' && 'squash' || 'merge' }} "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
