name: ci

on:
  push:
    paths:
      - '**/Dockerfile'
      - '**/toolsets/*.json'
  pull_request:
    paths:
      - '**/Dockerfile'
      - '**/toolsets/*.json'
      - '**/.github/workflows/ci.yml'

permissions:
  contents: read
  pull-requests: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.triggering_actor != 'github-actions[bot]'
    strategy:
      matrix:
        include:
          - from-version: '22.04'
            from-version-major: '22'
            from-version-minor: '04'
            distro: 'ubuntu'
            codename: 'jammy'
            from-flavor: 'act'
          - from-version: '20.04'
            from-version-major: '20'
            from-version-minor: '04'
            distro: 'ubuntu'
            codename: 'focal'
            from-flavor: 'act'
    env:
      REGISTRY: docker.io
      IMAGE_NAME: ubuntu-act
      IMAGE_REPOSITORY: ${{ format('{0}/{1}', github.repository_owner, 'ubuntu-act') }}
      SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
        with:
          ref: ${{ env.SHA }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2.1.0
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ format('{0}/{1}', env.REGISTRY, env.IMAGE_REPOSITORY) }}
          tags: |
            type=raw,value=${{ matrix.from-version }},enable={{is_default_branch}},priority=900
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') && matrix.from-version == '22.04' }},priority=700
            type=ref,event=branch,prefix=${{ matrix.from-version }}-,priority=600
            type=sha,prefix=${{ matrix.from-version }}-,format=short,priority=100
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ env.SHA }}
            org.opencontainers.image.ref.name=${{ github.ref_name }}
            org.opencontainers.image.created={{date 'dddd, MMMM Do YYYY, h:mm:ss a'}}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.authors='["${{ github.repositoryUrl}}","${{ github.actor }}"]'
            org.opencontainers.image.url=https://github.com/${{ github.repository }}/tree/${{ github.head_ref || github.ref_name }}/linux/${{ matrix.distro }}/
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.documentation=${{ github.repositoryUrl }}
            org.opencontainers.image.title=${{ env.IMAGE_REPOSITORY }}:${{ github.head_ref || github.ref_name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./linux/ubuntu/Dockerfile
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            FROM_IMAGE=buildpack-deps
            FROM_VERSION_MAJOR=${{ matrix.from-version-major }}
            FROM_VERSION_MINOR=${{ matrix.from-version-minor }}
            FROM_FLAVOR=${{ matrix.from-flavor }}
            DISTRO=${{ matrix.distro }}
            CODENAME=${{ matrix.codename }}
          cache-from: |
            type=registry,ref=${{ format('{0}/{1}', env.REGISTRY, env.IMAGE_REPOSITORY) }}:${{ github.head_ref || github.ref_name }}
            type=registry,ref=${{ format('{0}/{1}', env.REGISTRY, env.IMAGE_REPOSITORY) }}:cache-${{ matrix.codename }}
          cache-to: |
            type=registry,ref=${{ format('{0}/{1}', env.REGISTRY, env.IMAGE_REPOSITORY) }}:cache-${{ matrix.codename }},mode=max
          provenance: mode=max
          sbom: true
          push: ${{ github.event_name == 'push' && ! contains(fromJson('["dependabot[bot]","nektos/act"]'),github.actor) }}
          # outputs: type=image,oci-mediatypes=true,push=true

      - name: Docker Scout
        id: docker-scout
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/scout-action@v0.23.2
        with:
          command: quickview,compare
          image: ${{ steps.meta.outputs.tags }}
          to: ${{ format('{0}/{1}:{2}', env.REGISTRY, env.IMAGE_REPOSITORY, matrix.from-version) }}
          ignore-unchanged: true
          only-severities: critical,high
          github-token: ${{ secrets.GITHUB_TOKEN }}
          write-comment: true

  approve-pr:
    name: Approve PR
    runs-on: ubuntu-latest
    needs: [build]
    if: contains(fromJson('["mauwii","dependabot[bot]"]'), github.triggering_actor) && github.event_name == 'pull_request' &&  needs.build.result == 'success'
    steps:
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # - name: Merge PR
      #   run: gh pr merge --auto --merge "$PR_URL"
      #   env:
      #     PR_URL: ${{github.event.pull_request.html_url}}
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Clean cache
        run: |
          gh extension install actions/gh-actions-cache

          REPO=${{ github.repository }}
          BRANCH=refs/heads/${{ github.head_ref }}

          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R "${REPO}" -B "${BRANCH}" | cut -f 1)

          if [ -n "$cacheKeysForPR" ]; then
              ## Setting this to not fail the workflow while deleting cache keys.
              set +e
              echo "Deleting caches..."
              for cacheKey in $cacheKeysForPR; do
                  gh actions-cache delete "${cacheKey}" -R "${REPO}" -B "${BRANCH}" --confirm
              done
              echo "Done"
              ## Restore the fail on error.
              set -e
          else
              echo "No cache keys found for this PR"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
