name: ci

on:
  push:
    paths:
      - '**/Dockerfile'
      - './README.md'
  pull_request:
    paths:
      - '**/Dockerfile'
      - '**/.github/workflows/ci.yml'

permissions:
  contents: read
  pull-requests: write
  packages: write
  actions: write

env:
  IMAGE_NAME: ${{ github.repository_owner }}/ubuntu-act
  github-token: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.triggering_actor != 'github-actions[bot]'
    strategy:
      matrix:
        include:
          - from-version: '22.04'
            from-version-major: '22'
            from-version-minor: '04'
            distro: 'ubuntu'
            codename: 'jammy'
            from-flavor: 'act'
          - from-version: '20.04'
            from-version-major: '20'
            from-version-minor: '04'
            distro: 'ubuntu'
            codename: 'focal'
            from-flavor: 'act'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Create tags for docker buildx
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ${{ env.IMAGE_NAME }}
            ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' && matrix.from-version == '22.04' }}
            type=raw,value=${{ matrix.from-version }},enable=${{ github.ref == 'refs/heads/main' }}
            type=schedule
            type=ref,event=branch,prefix=${{ matrix.from-version }}-
            type=ref,event=pr
            type=sha,prefix=${{ matrix.from-version }}-,enable=${{ github.ref == 'refs/heads/main' }}
          labels: |
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.authors=['${{ github.repositoryUrl}}','${{ github.actor }}']
            org.opencontainers.image.url=https://github.com/${{ github.repository }}/tree/${{ github.head_ref || github.ref_name }}/linux/${{ matrix.distro }}/
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.documentation=${{ github.repositoryUrl }}
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}-${{ github.base_ref || github.ref_name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./linux/ubuntu/Dockerfile
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            FROM_IMAGE=buildpack-deps
            FROM_VERSION_MAJOR=${{ matrix.from-version-major }}
            FROM_VERSION_MINOR=${{ matrix.from-version-minor }}
            FROM_FLAVOR=${{ matrix.from-flavor }}
            DISTRO=${{ matrix.distro }}
            CODENAME=${{ matrix.codename }}
          cache-from: |
            type=registry,ref=docker.io/${{ env.IMAGE_NAME }}:${{ github.head_ref || github.ref_name }}
            type=registry,ref=docker.io/${{ env.IMAGE_NAME }}:${{ matrix.codename }}-cache
          cache-to: |
            type=registry,ref=docker.io/${{ env.IMAGE_NAME }}:${{ matrix.codename }}-cache,mode=max
          provenance: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          outputs: type=image,name=${{ env.IMAGE_NAME }},oci-mediatypes=true,push=${{ github.event_name == 'push' }}

  approve-pr:
    name: Approve PR
    runs-on: ubuntu-latest
    needs: [build]
    if: github.triggering_actor == 'mauwii' && github.event_name == 'pull_request' &&  needs.build.result == 'success'
    steps:
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # - name: Merge PR
      #   run: gh pr merge --auto --merge "$PR_URL"
      #   env:
      #     PR_URL: ${{github.event.pull_request.html_url}}
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Clean cache
        run: |
          gh extension install actions/gh-actions-cache

          REPO=${{ github.repository }}
          BRANCH=refs/heads/${{ github.head_ref }}

          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R "${REPO}" -B "${BRANCH}" | cut -f 1)

          if [ -n "$cacheKeysForPR" ]; then
              ## Setting this to not fail the workflow while deleting cache keys.
              set +e
              echo "Deleting caches..."
              for cacheKey in $cacheKeysForPR; do
                  gh actions-cache delete "${cacheKey}" -R "${REPO}" -B "${BRANCH}" --confirm
              done
              echo "Done"
              ## Restore the fail on error.
              set -e
          else
              echo "No cache keys found for this PR"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
