---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Docker-Hub description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

permissions:
  contents: read

jobs:
  dockerHubDescription:
    name: Update Docker-Hub description
    runs-on: ubuntu-latest
    # Ensure this job only runs if the Docker-Hub user is set
    if: vars.DOCKERHUB_USERNAME != ''
    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ format('{0}/{1}', vars.DOCKERHUB_USERNAME, 'ubuntu-act') }}
          short-description: ${{ github.event.repository.description }}
