---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Docker-Hub description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

permissions:
  contents: read

jobs:
  dockerHubDescription:
    name: Update Docker-Hub description
    runs-on: ubuntu-latest
    # Ensure this job only runs if the Docker-Hub user is set
    if: vars.DOCKERHUB_USERNAME != ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@dc67fad7001ef9e8e3c124cb7a64e16d0a63d864
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ format('{0}/{1}', vars.DOCKERHUB_USER, 'ubuntu-act') }}
          short-description: ${{ github.event.repository.description }}
