# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Docker-Hub description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

permissions:
  contents: read

jobs:
  dockerHubDescription:
    name: Update Docker-Hub description
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@dc67fad7001ef9e8e3c124cb7a64e16d0a63d864
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.repository_owner }}/ubuntu-act
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
